[colors]
background = '#0e1416'
foreground = '#dee3e5'

cursor_bg = '#00bcd4'
cursor_fg = '#0e1416'
cursor_border = '#00bcd4'

selection_bg = '#004d5c'
selection_fg = '#dee3e5'

ansi = ['#0e1416', '#e64c4f', '#76d66e', '#dbcc7b', '#1f8e9c', '#1f909f', '#00bcd4', '#abb2bf']
brights = ['#5c6370', '#e05f66', '#8de086', '#e8db97', '#4de7ff', '#2d857f', '#4c8191', '#ffffff']
