[colors]
background = '#000008'
foreground = '#e6f0ff'

cursor_bg = '#a4c8f1'
cursor_fg = '#000008'
cursor_border = '#a4c8f1'

selection_bg = '#0080ff'
selection_fg = '#e6f0ff'

ansi = ['#0A0A15', '#e34944', '#71d66e', '#dbd17b', '#5382bc', '#869cb4', '#a4c8f1', '#abb2bf']
brights = ['#5c6370', '#e05f60', '#88e086', '#e8df97', '#b1d8ff', '#467d9c', '#6278a6', '#ffffff']
